package com.broadway.has.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flowCommand.proto

public final class FlowCommand {
  private FlowCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlowCommandMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FlowCommandMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 pinNumber = 1;</code>
     */
    boolean hasPinNumber();
    /**
     * <code>optional int32 pinNumber = 1;</code>
     */
    int getPinNumber();

    /**
     * <code>optional bool isOn = 2;</code>
     */
    boolean hasIsOn();
    /**
     * <code>optional bool isOn = 2;</code>
     */
    boolean getIsOn();

    /**
     * <code>optional int32 runTimeMs = 3;</code>
     */
    boolean hasRunTimeMs();
    /**
     * <code>optional int32 runTimeMs = 3;</code>
     */
    int getRunTimeMs();
  }
  /**
   * Protobuf type {@code FlowCommandMessage}
   */
  public  static final class FlowCommandMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FlowCommandMessage)
      FlowCommandMessageOrBuilder {
    // Use FlowCommandMessage.newBuilder() to construct.
    private FlowCommandMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlowCommandMessage() {
      pinNumber_ = 0;
      isOn_ = false;
      runTimeMs_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlowCommandMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pinNumber_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isOn_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              runTimeMs_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FlowCommand.internal_static_FlowCommandMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FlowCommand.internal_static_FlowCommandMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FlowCommandMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int PINNUMBER_FIELD_NUMBER = 1;
    private int pinNumber_;
    /**
     * <code>optional int32 pinNumber = 1;</code>
     */
    public boolean hasPinNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 pinNumber = 1;</code>
     */
    public int getPinNumber() {
      return pinNumber_;
    }

    public static final int ISON_FIELD_NUMBER = 2;
    private boolean isOn_;
    /**
     * <code>optional bool isOn = 2;</code>
     */
    public boolean hasIsOn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isOn = 2;</code>
     */
    public boolean getIsOn() {
      return isOn_;
    }

    public static final int RUNTIMEMS_FIELD_NUMBER = 3;
    private int runTimeMs_;
    /**
     * <code>optional int32 runTimeMs = 3;</code>
     */
    public boolean hasRunTimeMs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 runTimeMs = 3;</code>
     */
    public int getRunTimeMs() {
      return runTimeMs_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pinNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isOn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, runTimeMs_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pinNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isOn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, runTimeMs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FlowCommandMessage)) {
        return super.equals(obj);
      }
      FlowCommandMessage other = (FlowCommandMessage) obj;

      boolean result = true;
      result = result && (hasPinNumber() == other.hasPinNumber());
      if (hasPinNumber()) {
        result = result && (getPinNumber()
            == other.getPinNumber());
      }
      result = result && (hasIsOn() == other.hasIsOn());
      if (hasIsOn()) {
        result = result && (getIsOn()
            == other.getIsOn());
      }
      result = result && (hasRunTimeMs() == other.hasRunTimeMs());
      if (hasRunTimeMs()) {
        result = result && (getRunTimeMs()
            == other.getRunTimeMs());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPinNumber()) {
        hash = (37 * hash) + PINNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPinNumber();
      }
      if (hasIsOn()) {
        hash = (37 * hash) + ISON_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsOn());
      }
      if (hasRunTimeMs()) {
        hash = (37 * hash) + RUNTIMEMS_FIELD_NUMBER;
        hash = (53 * hash) + getRunTimeMs();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FlowCommandMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FlowCommandMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FlowCommandMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FlowCommandMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FlowCommandMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FlowCommandMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FlowCommandMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FlowCommandMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FlowCommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FlowCommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FlowCommandMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FlowCommandMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FlowCommandMessage)
        FlowCommandMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FlowCommand.internal_static_FlowCommandMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FlowCommand.internal_static_FlowCommandMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FlowCommandMessage.class, Builder.class);
      }

      // Construct using FlowCommand.FlowCommandMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pinNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isOn_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        runTimeMs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FlowCommand.internal_static_FlowCommandMessage_descriptor;
      }

      public FlowCommandMessage getDefaultInstanceForType() {
        return FlowCommandMessage.getDefaultInstance();
      }

      public FlowCommandMessage build() {
        FlowCommandMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FlowCommandMessage buildPartial() {
        FlowCommandMessage result = new FlowCommandMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pinNumber_ = pinNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isOn_ = isOn_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.runTimeMs_ = runTimeMs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FlowCommandMessage) {
          return mergeFrom((FlowCommandMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FlowCommandMessage other) {
        if (other == FlowCommandMessage.getDefaultInstance()) return this;
        if (other.hasPinNumber()) {
          setPinNumber(other.getPinNumber());
        }
        if (other.hasIsOn()) {
          setIsOn(other.getIsOn());
        }
        if (other.hasRunTimeMs()) {
          setRunTimeMs(other.getRunTimeMs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FlowCommandMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FlowCommandMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pinNumber_ ;
      /**
       * <code>optional int32 pinNumber = 1;</code>
       */
      public boolean hasPinNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 pinNumber = 1;</code>
       */
      public int getPinNumber() {
        return pinNumber_;
      }
      /**
       * <code>optional int32 pinNumber = 1;</code>
       */
      public Builder setPinNumber(int value) {
        bitField0_ |= 0x00000001;
        pinNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pinNumber = 1;</code>
       */
      public Builder clearPinNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pinNumber_ = 0;
        onChanged();
        return this;
      }

      private boolean isOn_ ;
      /**
       * <code>optional bool isOn = 2;</code>
       */
      public boolean hasIsOn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isOn = 2;</code>
       */
      public boolean getIsOn() {
        return isOn_;
      }
      /**
       * <code>optional bool isOn = 2;</code>
       */
      public Builder setIsOn(boolean value) {
        bitField0_ |= 0x00000002;
        isOn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isOn = 2;</code>
       */
      public Builder clearIsOn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isOn_ = false;
        onChanged();
        return this;
      }

      private int runTimeMs_ ;
      /**
       * <code>optional int32 runTimeMs = 3;</code>
       */
      public boolean hasRunTimeMs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 runTimeMs = 3;</code>
       */
      public int getRunTimeMs() {
        return runTimeMs_;
      }
      /**
       * <code>optional int32 runTimeMs = 3;</code>
       */
      public Builder setRunTimeMs(int value) {
        bitField0_ |= 0x00000004;
        runTimeMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 runTimeMs = 3;</code>
       */
      public Builder clearRunTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        runTimeMs_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FlowCommandMessage)
    }

    // @@protoc_insertion_point(class_scope:FlowCommandMessage)
    private static final FlowCommandMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FlowCommandMessage();
    }

    public static FlowCommandMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<FlowCommandMessage>
        PARSER = new com.google.protobuf.AbstractParser<FlowCommandMessage>() {
      public FlowCommandMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FlowCommandMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlowCommandMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FlowCommandMessage> getParserForType() {
      return PARSER;
    }

    public FlowCommandMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FlowCommandMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FlowCommandMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021flowCommand.proto\"H\n\022FlowCommandMessag" +
      "e\022\021\n\tpinNumber\030\001 \001(\005\022\014\n\004isOn\030\002 \001(\010\022\021\n\tru" +
      "nTimeMs\030\003 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FlowCommandMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FlowCommandMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FlowCommandMessage_descriptor,
        new String[] { "PinNumber", "IsOn", "RunTimeMs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
