package com.broadway.has.repositories;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.broadway.has.messaging.WateringRequest;
import com.broadway.has.messaging.XbeeCommand;

import java.util.Date;
import java.util.Map;

@DynamoDBTable(tableName = "CommandRunHistory")
public class CommandHistoryDao {

    private String id;
    private Date dateExecuted;
    private boolean isSendSuccess;
    private String error;
    private String commandType;
    //private Map<String, Object> jsonObject;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Date getDateExecuted() {
        return dateExecuted;
    }

    public void setDateExecuted(Date dateExecuted) {
        this.dateExecuted = dateExecuted;
    }

    @DynamoDBAttribute
    public boolean isSendSuccess() {
        return isSendSuccess;
    }

    public void setSendSuccess(boolean sendSuccess) {
        isSendSuccess = sendSuccess;
    }

    @DynamoDBAttribute
    public String getCommandType() {
        return commandType;
    }

    public void setCommandType(String commandType) {
        this.commandType = commandType;
    }

    public Map<String, Object> getJsonObject() {
        return null;//jsonObject;
    }

    public void setJsonObject(Map<String, Object> jsonObject) {
        //this.jsonObject = jsonObject;
    }

    @DynamoDBAttribute
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }
}
